name: Build Shiv Package

on:
  push:
    tags:
      - '*'  # Trigger für alle Tags
  workflow_dispatch:  # Ermöglicht manuelles Starten

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Aktualisiere auf v3

    - name: Set up Python
      uses: actions/setup-python@v4  # Aktualisiere auf v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install shiv

    - name: Build Shiv package
      run: |
        shiv --site-packages . -o frameshare.pyz -e main:main -r requirements.txt

    - name: Upload Shiv package
      uses: actions/upload-artifact@v4  # Aktualisiere auf v4
      with:
        name: frameshare
        path: frameshare.pyz
