name: Build and Release Shiv Package

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install shiv

    - name: Build Shiv package
      run: |
        shiv --site-packages . -o frameshare.pyz -e main:main -r requirements.txt

    - name: Create Git Tag
      run: |
        git tag ${{ github.event.inputs.tag_name }}
        git push origin ${{ github.event.inputs.tag_name }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: frameshare.pyz
        tag_name: ${{ github.event.inputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
