name: Build and Release Shiv Package

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Installiere NumPy mit vorkompilierten Binärpaketen (no-binary Option ist hier wichtig)
        pip install numpy --no-binary :all:
        pip install -r requirements.txt
        pip install shiv

    - name: Build Shiv package
      run: |
        # Baue das Shiv-Paket unter Verwendung von compressed, compile-pyc und definiere site-packages
        shiv --compressed --compile-pyc --site-packages $(python -m site --user-site) -o frameshare.pyz -e main:main

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Push Git Tag
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git tag ${{ github.event.inputs.tag_name }}
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} ${{ github.event.inputs.tag_name }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: frameshare.pyz
        tag_name: ${{ github.event.inputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
